import customtkinter as ctk
def suma():
    suma=int(entrada.get())+int(entrada2.get())+int(entrada3.get())
    mostrar.configure(text=suma)
    mostrar.configure(text=Resta)
ventana=ctk.CTk()
ventana.geometry("1000x1000")
ventana.title("massay")
ctk.set_appearance_mode("dark")
entrada=ctk.CTkEntry(ventana, placeholder_text="Escriba un numero")
entrada.pack(pady=10,padx=10)
entrada2=ctk.CTkEntry(ventana, placeholder_text="Escriba un numero")
entrada2.pack(pady=10,padx=10)
entrada3=ctk.CTkEntry(ventana, placeholder_text="Escriba un numero")
entrada3.pack(pady=10,padx=10)
boton = ctk.CTkButton(ventana, text="Sumar", command=suma)
boton.pack(pady=10,padx=10)
boton2 = ctk.CTkButton(ventana, text="Restar", command=Resta)
boton2.pack(pady=10,padx=10)
mostrar=ctk.CTkLabel(ventana, text="", fg_color="transparent")
mostrar.pack(pady=10,padx=10)
ventana.mainloop()
